import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#FFE9C9]`}>
        <div className="px-[20px] py-[5px] flex justify-between items-center border-b-[1px] border-[#523636]">
          <Image className="w-[80px] h-[auto]" src={'/wangohan_logo.png'} width={100} height={100} alt="website logo" />
          <div className={'menu flex gap-[1rem]'}>
            <div className="self-center">
              <Image src={'/icons/notification.png'} className="self-center rounded-md h-[auto] w-[40px] relative" width={10000} height={10000}  alt="website banner" />
            </div>
            <div className="self-center">
              <Image src={'/icons/bone.png'} className="self-center rounded-md h-[auto] w-[50px] relative" width={10000} height={10000}  alt="website banner" />
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
